# Generated by Django 5.2.11 on 2026-03-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClonacionBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clonacion', models.DateTimeField(auto_now_add=True)),
                ('motor_base', models.CharField(max_length=100)),
                ('origen_path', models.CharField(max_length=500)),
                ('destino_path', models.CharField(max_length=500)),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=500)),
                ('base_activa_actualizada_at', models.DateTimeField(blank=True, null=True)),
                ('base_activa_size_bytes', models.BigIntegerField(default=0)),
                ('destino_size_bytes', models.BigIntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clonaciones_bd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clonación de Base de Datos',
                'verbose_name_plural': 'Clonaciones de Base de Datos',
                'ordering': ('-fecha_clonacion',),
            },
        ),
    ]
