# Generated by Django 5.2.4 on 2026-09-26 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0014_producto_estado_operativo_producto_fecha_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCambioPrecioCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('REVISAR', 'Revisar')], default='OK', max_length=10)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('revisado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_cambios_precio_compra', to=settings.AUTH_USER_MODEL)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_cambio_precio_compra', to='Pedidos.stock')),
            ],
            options={
                'verbose_name': 'Revision de cambio de precio de compra',
                'verbose_name_plural': 'Revisiones de cambios de precio de compra',
                'ordering': ('-revisado_en', '-id'),
            },
        ),
    ]
