# Generated by Django 5.2.4 on 2025-08-14 16:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaEmpaque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("PRIMARIO", "Primario"),
                            ("SECUNDARIO", "Secundario"),
                            ("TERCIARIO", "Terciario"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=30)),
                ("rut_cliente", models.CharField(max_length=20, unique=True)),
                ("direccion_cliente", models.CharField(max_length=100)),
                ("direccion_bodega_cliente", models.CharField(max_length=100)),
                ("cliente_activo", models.BooleanField(default=True)),
                ("telefono_cliente", models.CharField(max_length=30)),
                ("correo_cliente", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PERSONA NATURAL", "PERSONA NATURAL"),
                            ("EMPRESA PRIVADA", "EMPRESA PRIVADA"),
                            ("EMPRESA PÚBLICA", "EMPRESA PÚBLICA"),
                            ("PYME", "PYME"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_proveedor", models.CharField(max_length=30)),
                ("rut_proveedor", models.CharField(max_length=20, unique=True)),
                ("direccion_proveedor", models.CharField(max_length=100)),
                ("direccion_bodega_proveedor", models.CharField(max_length=100)),
                ("empresa_activa", models.BooleanField(default=True)),
                ("banco_proveedor", models.CharField(max_length=20)),
                (
                    "cta_proveedor",
                    models.CharField(
                        choices=[
                            ("Corriente", "Corriente"),
                            ("Vista", "Vista"),
                            ("Prepago", "Prepago"),
                            ("Ahorro", "Ahorro"),
                            ("RUT", "RUT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("num_cuenta_proveedor", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_cotizacion", models.DateField()),
                (
                    "num_cotizacion",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="cotizaciones_pdfs/"
                    ),
                ),
                (
                    "nombre_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField()),
                (
                    "estado_pedido",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Entregado", "Entregado"),
                            ("Pagado", "Pagado"),
                            ("Finalizado", "Finalizado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comentario_pedido", models.TextField(blank=True, null=True)),
                (
                    "nombre_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.cliente",
                    ),
                ),
                (
                    "num_cotizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.cotizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntregaPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_receptor", models.CharField(max_length=120)),
                ("rut_receptor", models.CharField(max_length=20)),
                ("fecha_entrega", models.DateTimeField()),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="entregas_pdf/%Y/%m/"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="entregas_fotos/%Y/%m/"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="Pedidos.pedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_producto_proveedor", models.CharField(max_length=10)),
                ("codigo_producto_interno", models.CharField(max_length=10)),
                ("nombre_producto", models.CharField(max_length=40)),
                ("qty_terciario", models.IntegerField()),
                ("qty_secundario", models.IntegerField()),
                ("qty_primario", models.IntegerField()),
                ("qty_unidad", models.IntegerField()),
                (
                    "medida",
                    models.CharField(
                        choices=[
                            ("cms", "cms"),
                            ("mts", "mts"),
                            ("cc", "cc"),
                            ("ml", "ml"),
                            ("lts", "lts"),
                            ("und", "und"),
                            ("kg", "kg"),
                            ("grs", "grs"),
                        ],
                        max_length=5,
                    ),
                ),
                ("qty_minima", models.IntegerField()),
                (
                    "categoria_producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.categoria",
                    ),
                ),
                (
                    "empaque_primario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos_primarios",
                        to="Pedidos.categoriaempaque",
                    ),
                ),
                (
                    "empaque_secundario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos_secundarios",
                        to="Pedidos.categoriaempaque",
                    ),
                ),
                (
                    "empaque_terciario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos_terciarios",
                        to="Pedidos.categoriaempaque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListaPrecios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empaque", models.CharField(max_length=10)),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "precio_iva",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("vigencia", models.DateField()),
                (
                    "nombre_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.cliente",
                    ),
                ),
                (
                    "nombre_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_recepcion", models.DateField()),
                (
                    "estado_recepcion",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Recibido", "Recibido"),
                            ("Parcial", "Parcial"),
                            ("Rechazado", "Rechazado"),
                            ("Finalizado", "Finalziado"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "documento_recepcion",
                    models.CharField(
                        choices=[
                            ("Factura", "Factura"),
                            ("Guia de Despacho", "Guía de Despacho"),
                            ("Boleta", "Boleta"),
                            ("Credito", "Crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_documento_recepcion", models.IntegerField()),
                (
                    "total_neto_recepcion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "iva_recepcion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_recepcion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("incluir_iva", models.BooleanField(default=True)),
                (
                    "moneda_recepcion",
                    models.CharField(
                        choices=[
                            ("CLP", "CLP"),
                            ("EUR", "EUR"),
                            ("US", "US"),
                            ("UF", "UF"),
                            ("UTM", "UTM"),
                        ],
                        max_length=4,
                    ),
                ),
                ("comentario_recepcion", models.TextField(blank=True, null=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("RECEPCION", "Recepción"),
                            ("DISPONIBLE", "Disponible"),
                            ("RESERVA", "Reserva"),
                            ("DESPACHO", "Despacho"),
                        ],
                        max_length=10,
                    ),
                ),
                ("qty", models.IntegerField()),
                ("empaque", models.CharField(max_length=10)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("fecha_movimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Pedidos.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.producto",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Pedidos.recepcion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcategoria", models.CharField(max_length=30)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.categoria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="subcategoria_producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Pedidos.subcategoria",
            ),
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_venta", models.DateField()),
                (
                    "documento_pedido",
                    models.CharField(
                        choices=[
                            ("Factura", "Factura"),
                            ("Guia de Despacho", "Guía de Despacho"),
                            ("Boleta", "Boleta"),
                            ("Credito", "Crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_documento", models.IntegerField()),
                (
                    "venta_neto_pedido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "venta_iva_pedido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "venta_total_pedido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ganancia_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ganancia_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pedidoid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Pedidos.pedido"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_contacto", models.CharField(max_length=30)),
                ("apellido_contacto", models.CharField(max_length=30)),
                ("cargo_contacto", models.CharField(max_length=30)),
                ("telefono_contacto", models.CharField(max_length=30)),
                ("correo_contacto", models.CharField(max_length=50)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.proveedor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "proveedor",
                            "nombre_contacto",
                            "apellido_contacto",
                            "cargo_contacto",
                        ),
                        name="uniq_contacto_por_proveedor_nombre_apellido_cargo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UtilidadProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empaque", models.CharField(max_length=20)),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "precio_compra_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "precio_venta_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("utilidad", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "utilidad_porcentaje",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pedidos.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilidades",
                        to="Pedidos.venta",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["venta"], name="Pedidos_uti_venta_i_19052c_idx"
                    ),
                    models.Index(
                        fields=["producto"], name="Pedidos_uti_product_2628ac_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "venta",
                        "producto",
                        "empaque",
                        "precio_compra_unitario",
                        "precio_venta_unitario",
                    )
                },
            },
        ),
    ]
