# Generated by Django 5.1.3 on 2025-08-25 21:05

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.CharField(
                        db_index=True,
                        help_text="Código que el proveedor utiliza para este producto",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Proveedor",
                "verbose_name_plural": "Códigos de Proveedor",
            },
        ),
        migrations.AlterModelOptions(
            name="categoriaempaque",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveField(
            model_name="producto",
            name="codigo_producto_proveedor",
        ),
        migrations.AlterField(
            model_name="categoriaempaque",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recepcion",
            name="estado_recepcion",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Recibido", "Recibido"),
                    ("Parcial", "Parcial"),
                    ("Rechazado", "Rechazado"),
                    ("Finalizado", "Finalizado"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriaempaque",
            constraint=models.UniqueConstraint(
                fields=("nombre", "nivel"), name="uniq_categoria_empaque_nombre_nivel"
            ),
        ),
        migrations.AddField(
            model_name="codigoproveedor",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codigos_proveedor",
                to="Pedidos.producto",
            ),
        ),
        migrations.AddField(
            model_name="codigoproveedor",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codigos_proveedor",
                to="Pedidos.proveedor",
            ),
        ),
        migrations.AddConstraint(
            model_name="codigoproveedor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo_proveedor"),
                models.F("proveedor"),
                name="uniq_codigo_por_proveedor_ci",
            ),
        ),
    ]
