# Generated by Django 5.1.3 on 2025-08-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0002_codigoproveedor_alter_categoriaempaque_options_and_more"),
    ]

    operations = []
