# Generated by Django 5.1.3 on 2025-08-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0003_create_codigoproveedor_fix"),
    ]

    operations = []
