# Generated by Django 5.2.4 on 2025-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0004_create_codigoproveedor_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nombre_cliente",
            field=models.CharField(max_length=50),
        ),
    ]
