# Generated by Django 5.2.4 on 2025-09-05 14:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_alter_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPreciosPredeterminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_listaprecios', models.CharField(max_length=80, unique=True)),
                ('descripcion_listaprecios', models.CharField(blank=True, default='', max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Precios (Predeterminada)',
                'verbose_name_plural': 'Listas de Precios (Predeterminadas)',
                'ordering': ('nombre_listaprecios',),
            },
        ),
        migrations.CreateModel(
            name='ListaPreciosPredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empaque', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario')], max_length=15)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vigencia', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('listaprecios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pedidos.listapreciospredeterminada')),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_predeterminados', to='Pedidos.producto')),
            ],
            options={
                'verbose_name': 'Ítem de Lista Predeterminada',
                'verbose_name_plural': 'Ítems de Lista Predeterminada',
                'ordering': ('nombre_producto__nombre_producto', 'empaque'),
                'indexes': [models.Index(fields=['listaprecios'], name='Pedidos_lis_listapr_981ddd_idx'), models.Index(fields=['nombre_producto'], name='Pedidos_lis_nombre__d2d381_idx'), models.Index(fields=['vigencia'], name='Pedidos_lis_vigenci_3b669b_idx')],
                'constraints': [models.UniqueConstraint(fields=('listaprecios', 'nombre_producto', 'empaque'), name='uniq_pred_lista_producto_empaque')],
            },
        ),
    ]
