# Generated by Django 5.2.11 on 2026-03-22 15:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_listapreciospredeterminada_listapreciospreditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStockHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('RECEPCION', 'Recepción'), ('DISPONIBLE', 'Disponible'), ('RESERVA', 'Reserva'), ('DESPACHO', 'Despacho')], max_length=10)),
                ('qty', models.IntegerField()),
                ('empaque', models.CharField(max_length=10)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_movimiento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock_historicos', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='Pedidos.stock')),
            ],
            options={
                'ordering': ('fecha_movimiento', 'id'),
                'indexes': [models.Index(fields=['fecha_movimiento'], name='Pedidos_mov_fecha_m_642aa3_idx'), models.Index(fields=['tipo_movimiento', 'fecha_movimiento'], name='Pedidos_mov_tipo_mo_9570f0_idx')],
            },
        ),
    ]
