# Generated by Django 5.0.6 on 2026-05-13 01:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0007_movimientostockhistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('PACK', 'Pack')], default='SIMPLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='entregas_fotos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PackComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empaque', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_pack', to='Pedidos.producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_packs', to='Pedidos.producto')),
            ],
            options={
                'verbose_name': 'Componente de Pack',
                'verbose_name_plural': 'Componentes de Pack',
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PedidoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linea', models.CharField(choices=[('PRODUCTO', 'Producto'), ('PACK', 'Pack')], default='PRODUCTO', max_length=10)),
                ('descripcion', models.CharField(max_length=120)),
                ('empaque', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='Pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='Pedidos.producto')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='linea_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='Pedidos.pedidolinea'),
        ),
        migrations.AddConstraint(
            model_name='packcomponente',
            constraint=models.UniqueConstraint(fields=('pack', 'producto', 'empaque'), name='uniq_pack_producto_empaque'),
        ),
        migrations.AddIndex(
            model_name='pedidolinea',
            index=models.Index(fields=['pedido'], name='Pedidos_ped_pedido__75e50c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidolinea',
            index=models.Index(fields=['producto'], name='Pedidos_ped_product_932706_idx'),
        ),
    ]
