# Generated by Django 5.0.6 on 2026-05-15 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_producto_tipo_producto_alter_entregapedido_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lista_precios_predeterminada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asociados', to='Pedidos.listapreciospredeterminada'),
        ),
        migrations.AddField(
            model_name='listaprecios',
            name='lista_predeterminada_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_cliente_sincronizados', to='Pedidos.listapreciospredeterminada'),
        ),
    ]
