# Generated by Django 5.2.4 on 2026-06-28 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0013_force_trim_stock_datetime_text_sqlite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_operativo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO_VENTA', 'Suspendido de venta'), ('SUSPENDIDO_COMPRA', 'Suspendido de compra'), ('DESCONTINUADO', 'Descontinuado')], db_index=True, default='ACTIVO', max_length=22),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='motivo_estado',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_estado_actualizado', to=settings.AUTH_USER_MODEL),
        ),
    ]
