# Generated by Django 5.2.4 on 2026-06-30 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0014_producto_estado_operativo_producto_fecha_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBoletaSii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Principal', max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('ambiente', models.CharField(choices=[('CERTIFICACION', 'Certificacion'), ('PRODUCCION', 'Produccion')], default='CERTIFICACION', max_length=20)),
                ('rut_emisor', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=120)),
                ('giro', models.CharField(max_length=120)),
                ('direccion_origen', models.CharField(max_length=120)),
                ('comuna_origen', models.CharField(max_length=80)),
                ('ciudad_origen', models.CharField(max_length=80)),
                ('resolucion_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('resolucion_fecha', models.DateField(blank=True, null=True)),
                ('certificado_alias', models.CharField(blank=True, default='', max_length=120)),
                ('ruta_caf_tipo_39', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion Boleta SII',
                'verbose_name_plural': 'Configuraciones Boleta SII',
                'ordering': ('-activa', 'nombre', 'id'),
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad_cliente',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna_cliente',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro_cliente',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='venta',
            name='num_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BoletaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('DATOS_INCOMPLETOS', 'Datos incompletos'), ('XML_PREPARADO', 'XML preparado'), ('PENDIENTE_ENVIO', 'Pendiente envio'), ('ENVIADA', 'Enviada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=24)),
                ('tipo_dte', models.PositiveSmallIntegerField(default=39)),
                ('folio', models.PositiveIntegerField(blank=True, null=True)),
                ('ambiente', models.CharField(blank=True, default='', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('errores_validacion', models.JSONField(blank=True, default=list)),
                ('xml_borrador', models.FileField(blank=True, null=True, upload_to='dte/boletas/%Y/%m/')),
                ('preparada_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('preparada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_preparadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta_electronica', to='Pedidos.venta')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas', to='Pedidos.configuracionboletasii')),
            ],
            options={
                'verbose_name': 'Boleta electronica',
                'verbose_name_plural': 'Boletas electronicas',
                'ordering': ('-actualizado', '-id'),
            },
        ),
    ]
