# Generated by Django 5.2.4 on 2026-07-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0015_configuracionboletasii_cliente_ciudad_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionboletasii',
            options={'ordering': ('-activa', 'nombre', 'id'), 'verbose_name': 'Configuracion SII DTE', 'verbose_name_plural': 'Configuraciones SII DTE'},
        ),
        migrations.AddField(
            model_name='configuracionboletasii',
            name='acteco_principal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionboletasii',
            name='correo_intercambio',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionboletasii',
            name='habilita_boleta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionboletasii',
            name='habilita_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionboletasii',
            name='ruta_caf_tipo_33',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
