# Generated by Django 5.0.6 on 2026-07-01 03:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0016_alter_configuracionboletasii_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionboletasii',
            name='monto_identificacion_receptor_boleta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
