# Generated by Django 5.2.4 on 2025-09-07 20:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observaciones', '0002_observacion_lista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_mayor', models.PositiveIntegerField(default=0)),
                ('version_menor', models.PositiveIntegerField(default=0)),
                ('version_patch', models.PositiveIntegerField(default=1)),
                ('impacto', models.CharField(choices=[('PATCH', 'Corrección (Z)'), ('MENOR', 'Funcionalidad menor (Y)'), ('MAYOR', 'Cambio mayor (X)')], max_length=10)),
                ('resumen', models.CharField(help_text='Resumen corto del cambio', max_length=200)),
                ('detalle', models.TextField(help_text='Descripción de la solución aplicada')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('observacion', models.OneToOneField(blank=True, help_text='Observación que originó este cambio (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_registro', to='observaciones.observacion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
