# Generated by Django 5.0.6 on 2026-05-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observaciones', '0003_versionregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionregistro',
            name='impacto',
            field=models.CharField(choices=[('SIN_CAMBIO', 'Sin cambio de version'), ('PATCH', 'Corrección (Z)'), ('MENOR', 'Funcionalidad menor (Y)'), ('MAYOR', 'Cambio mayor (X)')], max_length=10),
        ),
    ]
